//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://www.syspro.com/ns/utilities/")]
    public enum Language : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AUTO = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ENGLISH_US = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRENCH_CANADIAN = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DANISH = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DUTCH = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ENGLISH = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FINNISH = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FRENCH = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GERMAN = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ITALIAN = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NORWEGIAN = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PORTUGUESE = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SPANISH = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SWEDISH = 13,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogDetail", Namespace="http://www.syspro.com/ns/utilities/")]
    public enum LogDetail : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ldNoDebug = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ldDebug = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Instance", Namespace="http://www.syspro.com/ns/utilities/")]
    public enum Instance : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EncoreInstance_0 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EncoreInstance_1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EncoreInstance_2 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EncoreInstance_3 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EncoreInstance_4 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EncoreInstance_5 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EncoreInstance_6 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EncoreInstance_7 = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EncoreInstance_8 = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EncoreInstance_9 = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.syspro.com/ns/utilities/", ConfigurationName="ServiceReference1.utilitiesclassSoap")]
    public interface utilitiesclassSoap
    {
        
        // CODEGEN: Generating message contract since element name Operator from namespace http://www.syspro.com/ns/utilities/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/Logon", ReplyAction="*")]
        ServiceReference1.LogonResponse Logon(ServiceReference1.LogonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/Logon", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.LogonResponse> LogonAsync(ServiceReference1.LogonRequest request);
        
        // CODEGEN: Generating message contract since element name OperatorCode from namespace http://www.syspro.com/ns/utilities/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/Logon_With_String", ReplyAction="*")]
        ServiceReference1.Logon_With_StringResponse Logon_With_String(ServiceReference1.Logon_With_StringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/Logon_With_String", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.Logon_With_StringResponse> Logon_With_StringAsync(ServiceReference1.Logon_With_StringRequest request);
        
        // CODEGEN: Generating message contract since element name OperatorCode from namespace http://www.syspro.com/ns/utilities/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/Logon_With_ByteArray", ReplyAction="*")]
        ServiceReference1.Logon_With_ByteArrayResponse Logon_With_ByteArray(ServiceReference1.Logon_With_ByteArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/Logon_With_ByteArray", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.Logon_With_ByteArrayResponse> Logon_With_ByteArrayAsync(ServiceReference1.Logon_With_ByteArrayRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/utilities/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/Logoff", ReplyAction="*")]
        ServiceReference1.LogoffResponse Logoff(ServiceReference1.LogoffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/Logoff", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.LogoffResponse> LogoffAsync(ServiceReference1.LogoffRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/utilities/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/GetLogonProfile", ReplyAction="*")]
        ServiceReference1.GetLogonProfileResponse GetLogonProfile(ServiceReference1.GetLogonProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/GetLogonProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetLogonProfileResponse> GetLogonProfileAsync(ServiceReference1.GetLogonProfileRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/utilities/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/GetLogonProfileW", ReplyAction="*")]
        ServiceReference1.GetLogonProfileWResponse GetLogonProfileW(ServiceReference1.GetLogonProfileWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/GetLogonProfileW", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetLogonProfileWResponse> GetLogonProfileWAsync(ServiceReference1.GetLogonProfileWRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/utilities/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/GetLogonProfile_With_String", ReplyAction="*")]
        ServiceReference1.GetLogonProfile_With_StringResponse GetLogonProfile_With_String(ServiceReference1.GetLogonProfile_With_StringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/GetLogonProfile_With_String", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetLogonProfile_With_StringResponse> GetLogonProfile_With_StringAsync(ServiceReference1.GetLogonProfile_With_StringRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/utilities/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/GetLogonProfile_With_ByteArray", ReplyAction="*")]
        ServiceReference1.GetLogonProfile_With_ByteArrayResponse GetLogonProfile_With_ByteArray(ServiceReference1.GetLogonProfile_With_ByteArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/GetLogonProfile_With_ByteArray", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetLogonProfile_With_ByteArrayResponse> GetLogonProfile_With_ByteArrayAsync(ServiceReference1.GetLogonProfile_With_ByteArrayRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/utilities/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/Run", ReplyAction="*")]
        ServiceReference1.RunResponse Run(ServiceReference1.RunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/Run", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.RunResponse> RunAsync(ServiceReference1.RunRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/utilities/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/Run_With_String", ReplyAction="*")]
        ServiceReference1.Run_With_StringResponse Run_With_String(ServiceReference1.Run_With_StringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/utilities/Run_With_String", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.Run_With_StringResponse> Run_With_StringAsync(ServiceReference1.Run_With_StringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogonRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logon", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.LogonRequestBody Body;
        
        public LogonRequest()
        {
        }
        
        public LogonRequest(ServiceReference1.LogonRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class LogonRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Operator;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OperatorPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CompanyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CompanyPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public ServiceReference1.Language LanguageCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public ServiceReference1.LogDetail LogLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public ServiceReference1.Instance EncoreInstance;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string XmlIn;
        
        public LogonRequestBody()
        {
        }
        
        public LogonRequestBody(string Operator, string OperatorPassword, string CompanyId, string CompanyPassword, ServiceReference1.Language LanguageCode, ServiceReference1.LogDetail LogLevel, ServiceReference1.Instance EncoreInstance, string XmlIn)
        {
            this.Operator = Operator;
            this.OperatorPassword = OperatorPassword;
            this.CompanyId = CompanyId;
            this.CompanyPassword = CompanyPassword;
            this.LanguageCode = LanguageCode;
            this.LogLevel = LogLevel;
            this.EncoreInstance = EncoreInstance;
            this.XmlIn = XmlIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogonResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogonResponse", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.LogonResponseBody Body;
        
        public LogonResponse()
        {
        }
        
        public LogonResponse(ServiceReference1.LogonResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class LogonResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogonResult;
        
        public LogonResponseBody()
        {
        }
        
        public LogonResponseBody(string LogonResult)
        {
            this.LogonResult = LogonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Logon_With_StringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logon_With_String", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.Logon_With_StringRequestBody Body;
        
        public Logon_With_StringRequest()
        {
        }
        
        public Logon_With_StringRequest(ServiceReference1.Logon_With_StringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class Logon_With_StringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OperatorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OperatorPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CompanyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CompanyPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public ServiceReference1.Language LanguageCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public ServiceReference1.LogDetail LogLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public ServiceReference1.Instance EncoreInstance;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string XmlIn;
        
        public Logon_With_StringRequestBody()
        {
        }
        
        public Logon_With_StringRequestBody(string OperatorCode, string OperatorPassword, string CompanyId, string CompanyPassword, ServiceReference1.Language LanguageCode, ServiceReference1.LogDetail LogLevel, ServiceReference1.Instance EncoreInstance, string XmlIn)
        {
            this.OperatorCode = OperatorCode;
            this.OperatorPassword = OperatorPassword;
            this.CompanyId = CompanyId;
            this.CompanyPassword = CompanyPassword;
            this.LanguageCode = LanguageCode;
            this.LogLevel = LogLevel;
            this.EncoreInstance = EncoreInstance;
            this.XmlIn = XmlIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Logon_With_StringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logon_With_StringResponse", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.Logon_With_StringResponseBody Body;
        
        public Logon_With_StringResponse()
        {
        }
        
        public Logon_With_StringResponse(ServiceReference1.Logon_With_StringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class Logon_With_StringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Logon_With_StringResult;
        
        public Logon_With_StringResponseBody()
        {
        }
        
        public Logon_With_StringResponseBody(string Logon_With_StringResult)
        {
            this.Logon_With_StringResult = Logon_With_StringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Logon_With_ByteArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logon_With_ByteArray", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.Logon_With_ByteArrayRequestBody Body;
        
        public Logon_With_ByteArrayRequest()
        {
        }
        
        public Logon_With_ByteArrayRequest(ServiceReference1.Logon_With_ByteArrayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class Logon_With_ByteArrayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OperatorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OperatorPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CompanyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CompanyPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public ServiceReference1.Language LanguageCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public ServiceReference1.LogDetail LogLevel;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public ServiceReference1.Instance EncoreInstance;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public byte[] XmlIn;
        
        public Logon_With_ByteArrayRequestBody()
        {
        }
        
        public Logon_With_ByteArrayRequestBody(string OperatorCode, string OperatorPassword, string CompanyId, string CompanyPassword, ServiceReference1.Language LanguageCode, ServiceReference1.LogDetail LogLevel, ServiceReference1.Instance EncoreInstance, byte[] XmlIn)
        {
            this.OperatorCode = OperatorCode;
            this.OperatorPassword = OperatorPassword;
            this.CompanyId = CompanyId;
            this.CompanyPassword = CompanyPassword;
            this.LanguageCode = LanguageCode;
            this.LogLevel = LogLevel;
            this.EncoreInstance = EncoreInstance;
            this.XmlIn = XmlIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Logon_With_ByteArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logon_With_ByteArrayResponse", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.Logon_With_ByteArrayResponseBody Body;
        
        public Logon_With_ByteArrayResponse()
        {
        }
        
        public Logon_With_ByteArrayResponse(ServiceReference1.Logon_With_ByteArrayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class Logon_With_ByteArrayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Logon_With_ByteArrayResult;
        
        public Logon_With_ByteArrayResponseBody()
        {
        }
        
        public Logon_With_ByteArrayResponseBody(string Logon_With_ByteArrayResult)
        {
            this.Logon_With_ByteArrayResult = Logon_With_ByteArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoffRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logoff", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.LogoffRequestBody Body;
        
        public LogoffRequest()
        {
        }
        
        public LogoffRequest(ServiceReference1.LogoffRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class LogoffRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        public LogoffRequestBody()
        {
        }
        
        public LogoffRequestBody(string UserId)
        {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoffResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoffResponse", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.LogoffResponseBody Body;
        
        public LogoffResponse()
        {
        }
        
        public LogoffResponse(ServiceReference1.LogoffResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class LogoffResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogoffResult;
        
        public LogoffResponseBody()
        {
        }
        
        public LogoffResponseBody(string LogoffResult)
        {
            this.LogoffResult = LogoffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogonProfileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogonProfile", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.GetLogonProfileRequestBody Body;
        
        public GetLogonProfileRequest()
        {
        }
        
        public GetLogonProfileRequest(ServiceReference1.GetLogonProfileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class GetLogonProfileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        public GetLogonProfileRequestBody()
        {
        }
        
        public GetLogonProfileRequestBody(string UserId)
        {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogonProfileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogonProfileResponse", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.GetLogonProfileResponseBody Body;
        
        public GetLogonProfileResponse()
        {
        }
        
        public GetLogonProfileResponse(ServiceReference1.GetLogonProfileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class GetLogonProfileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLogonProfileResult;
        
        public GetLogonProfileResponseBody()
        {
        }
        
        public GetLogonProfileResponseBody(string GetLogonProfileResult)
        {
            this.GetLogonProfileResult = GetLogonProfileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogonProfileWRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogonProfileW", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.GetLogonProfileWRequestBody Body;
        
        public GetLogonProfileWRequest()
        {
        }
        
        public GetLogonProfileWRequest(ServiceReference1.GetLogonProfileWRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class GetLogonProfileWRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        public GetLogonProfileWRequestBody()
        {
        }
        
        public GetLogonProfileWRequestBody(string UserId)
        {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogonProfileWResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogonProfileWResponse", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.GetLogonProfileWResponseBody Body;
        
        public GetLogonProfileWResponse()
        {
        }
        
        public GetLogonProfileWResponse(ServiceReference1.GetLogonProfileWResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class GetLogonProfileWResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetLogonProfileWResult;
        
        public GetLogonProfileWResponseBody()
        {
        }
        
        public GetLogonProfileWResponseBody(byte[] GetLogonProfileWResult)
        {
            this.GetLogonProfileWResult = GetLogonProfileWResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogonProfile_With_StringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogonProfile_With_String", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.GetLogonProfile_With_StringRequestBody Body;
        
        public GetLogonProfile_With_StringRequest()
        {
        }
        
        public GetLogonProfile_With_StringRequest(ServiceReference1.GetLogonProfile_With_StringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class GetLogonProfile_With_StringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        public GetLogonProfile_With_StringRequestBody()
        {
        }
        
        public GetLogonProfile_With_StringRequestBody(string UserId)
        {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogonProfile_With_StringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogonProfile_With_StringResponse", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.GetLogonProfile_With_StringResponseBody Body;
        
        public GetLogonProfile_With_StringResponse()
        {
        }
        
        public GetLogonProfile_With_StringResponse(ServiceReference1.GetLogonProfile_With_StringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class GetLogonProfile_With_StringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLogonProfile_With_StringResult;
        
        public GetLogonProfile_With_StringResponseBody()
        {
        }
        
        public GetLogonProfile_With_StringResponseBody(string GetLogonProfile_With_StringResult)
        {
            this.GetLogonProfile_With_StringResult = GetLogonProfile_With_StringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogonProfile_With_ByteArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogonProfile_With_ByteArray", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.GetLogonProfile_With_ByteArrayRequestBody Body;
        
        public GetLogonProfile_With_ByteArrayRequest()
        {
        }
        
        public GetLogonProfile_With_ByteArrayRequest(ServiceReference1.GetLogonProfile_With_ByteArrayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class GetLogonProfile_With_ByteArrayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        public GetLogonProfile_With_ByteArrayRequestBody()
        {
        }
        
        public GetLogonProfile_With_ByteArrayRequestBody(string UserId)
        {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogonProfile_With_ByteArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogonProfile_With_ByteArrayResponse", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.GetLogonProfile_With_ByteArrayResponseBody Body;
        
        public GetLogonProfile_With_ByteArrayResponse()
        {
        }
        
        public GetLogonProfile_With_ByteArrayResponse(ServiceReference1.GetLogonProfile_With_ByteArrayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class GetLogonProfile_With_ByteArrayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetLogonProfile_With_ByteArrayResult;
        
        public GetLogonProfile_With_ByteArrayResponseBody()
        {
        }
        
        public GetLogonProfile_With_ByteArrayResponseBody(byte[] GetLogonProfile_With_ByteArrayResult)
        {
            this.GetLogonProfile_With_ByteArrayResult = GetLogonProfile_With_ByteArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Run", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.RunRequestBody Body;
        
        public RunRequest()
        {
        }
        
        public RunRequest(ServiceReference1.RunRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class RunRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Parameter;
        
        public RunRequestBody()
        {
        }
        
        public RunRequestBody(string UserId, string BusinessObject, string Parameter)
        {
            this.UserId = UserId;
            this.BusinessObject = BusinessObject;
            this.Parameter = Parameter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RunResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RunResponse", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.RunResponseBody Body;
        
        public RunResponse()
        {
        }
        
        public RunResponse(ServiceReference1.RunResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class RunResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RunResult;
        
        public RunResponseBody()
        {
        }
        
        public RunResponseBody(string RunResult)
        {
            this.RunResult = RunResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Run_With_StringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Run_With_String", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.Run_With_StringRequestBody Body;
        
        public Run_With_StringRequest()
        {
        }
        
        public Run_With_StringRequest(ServiceReference1.Run_With_StringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class Run_With_StringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Parameter;
        
        public Run_With_StringRequestBody()
        {
        }
        
        public Run_With_StringRequestBody(string UserId, string BusinessObject, string Parameter)
        {
            this.UserId = UserId;
            this.BusinessObject = BusinessObject;
            this.Parameter = Parameter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Run_With_StringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Run_With_StringResponse", Namespace="http://www.syspro.com/ns/utilities/", Order=0)]
        public ServiceReference1.Run_With_StringResponseBody Body;
        
        public Run_With_StringResponse()
        {
        }
        
        public Run_With_StringResponse(ServiceReference1.Run_With_StringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/utilities/")]
    public partial class Run_With_StringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Run_With_StringResult;
        
        public Run_With_StringResponseBody()
        {
        }
        
        public Run_With_StringResponseBody(string Run_With_StringResult)
        {
            this.Run_With_StringResult = Run_With_StringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface utilitiesclassSoapChannel : ServiceReference1.utilitiesclassSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class utilitiesclassSoapClient : System.ServiceModel.ClientBase<ServiceReference1.utilitiesclassSoap>, ServiceReference1.utilitiesclassSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public utilitiesclassSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(utilitiesclassSoapClient.GetBindingForEndpoint(endpointConfiguration), utilitiesclassSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public utilitiesclassSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(utilitiesclassSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public utilitiesclassSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(utilitiesclassSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public utilitiesclassSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.LogonResponse ServiceReference1.utilitiesclassSoap.Logon(ServiceReference1.LogonRequest request)
        {
            return base.Channel.Logon(request);
        }
        
        public string Logon(string Operator, string OperatorPassword, string CompanyId, string CompanyPassword, ServiceReference1.Language LanguageCode, ServiceReference1.LogDetail LogLevel, ServiceReference1.Instance EncoreInstance, string XmlIn)
        {
            ServiceReference1.LogonRequest inValue = new ServiceReference1.LogonRequest();
            inValue.Body = new ServiceReference1.LogonRequestBody();
            inValue.Body.Operator = Operator;
            inValue.Body.OperatorPassword = OperatorPassword;
            inValue.Body.CompanyId = CompanyId;
            inValue.Body.CompanyPassword = CompanyPassword;
            inValue.Body.LanguageCode = LanguageCode;
            inValue.Body.LogLevel = LogLevel;
            inValue.Body.EncoreInstance = EncoreInstance;
            inValue.Body.XmlIn = XmlIn;
            ServiceReference1.LogonResponse retVal = ((ServiceReference1.utilitiesclassSoap)(this)).Logon(inValue);
            return retVal.Body.LogonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.LogonResponse> ServiceReference1.utilitiesclassSoap.LogonAsync(ServiceReference1.LogonRequest request)
        {
            return base.Channel.LogonAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.LogonResponse> LogonAsync(string Operator, string OperatorPassword, string CompanyId, string CompanyPassword, ServiceReference1.Language LanguageCode, ServiceReference1.LogDetail LogLevel, ServiceReference1.Instance EncoreInstance, string XmlIn)
        {
            ServiceReference1.LogonRequest inValue = new ServiceReference1.LogonRequest();
            inValue.Body = new ServiceReference1.LogonRequestBody();
            inValue.Body.Operator = Operator;
            inValue.Body.OperatorPassword = OperatorPassword;
            inValue.Body.CompanyId = CompanyId;
            inValue.Body.CompanyPassword = CompanyPassword;
            inValue.Body.LanguageCode = LanguageCode;
            inValue.Body.LogLevel = LogLevel;
            inValue.Body.EncoreInstance = EncoreInstance;
            inValue.Body.XmlIn = XmlIn;
            return ((ServiceReference1.utilitiesclassSoap)(this)).LogonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.Logon_With_StringResponse ServiceReference1.utilitiesclassSoap.Logon_With_String(ServiceReference1.Logon_With_StringRequest request)
        {
            return base.Channel.Logon_With_String(request);
        }
        
        public string Logon_With_String(string OperatorCode, string OperatorPassword, string CompanyId, string CompanyPassword, ServiceReference1.Language LanguageCode, ServiceReference1.LogDetail LogLevel, ServiceReference1.Instance EncoreInstance, string XmlIn)
        {
            ServiceReference1.Logon_With_StringRequest inValue = new ServiceReference1.Logon_With_StringRequest();
            inValue.Body = new ServiceReference1.Logon_With_StringRequestBody();
            inValue.Body.OperatorCode = OperatorCode;
            inValue.Body.OperatorPassword = OperatorPassword;
            inValue.Body.CompanyId = CompanyId;
            inValue.Body.CompanyPassword = CompanyPassword;
            inValue.Body.LanguageCode = LanguageCode;
            inValue.Body.LogLevel = LogLevel;
            inValue.Body.EncoreInstance = EncoreInstance;
            inValue.Body.XmlIn = XmlIn;
            ServiceReference1.Logon_With_StringResponse retVal = ((ServiceReference1.utilitiesclassSoap)(this)).Logon_With_String(inValue);
            return retVal.Body.Logon_With_StringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Logon_With_StringResponse> ServiceReference1.utilitiesclassSoap.Logon_With_StringAsync(ServiceReference1.Logon_With_StringRequest request)
        {
            return base.Channel.Logon_With_StringAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Logon_With_StringResponse> Logon_With_StringAsync(string OperatorCode, string OperatorPassword, string CompanyId, string CompanyPassword, ServiceReference1.Language LanguageCode, ServiceReference1.LogDetail LogLevel, ServiceReference1.Instance EncoreInstance, string XmlIn)
        {
            ServiceReference1.Logon_With_StringRequest inValue = new ServiceReference1.Logon_With_StringRequest();
            inValue.Body = new ServiceReference1.Logon_With_StringRequestBody();
            inValue.Body.OperatorCode = OperatorCode;
            inValue.Body.OperatorPassword = OperatorPassword;
            inValue.Body.CompanyId = CompanyId;
            inValue.Body.CompanyPassword = CompanyPassword;
            inValue.Body.LanguageCode = LanguageCode;
            inValue.Body.LogLevel = LogLevel;
            inValue.Body.EncoreInstance = EncoreInstance;
            inValue.Body.XmlIn = XmlIn;
            return ((ServiceReference1.utilitiesclassSoap)(this)).Logon_With_StringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.Logon_With_ByteArrayResponse ServiceReference1.utilitiesclassSoap.Logon_With_ByteArray(ServiceReference1.Logon_With_ByteArrayRequest request)
        {
            return base.Channel.Logon_With_ByteArray(request);
        }
        
        public string Logon_With_ByteArray(string OperatorCode, string OperatorPassword, string CompanyId, string CompanyPassword, ServiceReference1.Language LanguageCode, ServiceReference1.LogDetail LogLevel, ServiceReference1.Instance EncoreInstance, byte[] XmlIn)
        {
            ServiceReference1.Logon_With_ByteArrayRequest inValue = new ServiceReference1.Logon_With_ByteArrayRequest();
            inValue.Body = new ServiceReference1.Logon_With_ByteArrayRequestBody();
            inValue.Body.OperatorCode = OperatorCode;
            inValue.Body.OperatorPassword = OperatorPassword;
            inValue.Body.CompanyId = CompanyId;
            inValue.Body.CompanyPassword = CompanyPassword;
            inValue.Body.LanguageCode = LanguageCode;
            inValue.Body.LogLevel = LogLevel;
            inValue.Body.EncoreInstance = EncoreInstance;
            inValue.Body.XmlIn = XmlIn;
            ServiceReference1.Logon_With_ByteArrayResponse retVal = ((ServiceReference1.utilitiesclassSoap)(this)).Logon_With_ByteArray(inValue);
            return retVal.Body.Logon_With_ByteArrayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Logon_With_ByteArrayResponse> ServiceReference1.utilitiesclassSoap.Logon_With_ByteArrayAsync(ServiceReference1.Logon_With_ByteArrayRequest request)
        {
            return base.Channel.Logon_With_ByteArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Logon_With_ByteArrayResponse> Logon_With_ByteArrayAsync(string OperatorCode, string OperatorPassword, string CompanyId, string CompanyPassword, ServiceReference1.Language LanguageCode, ServiceReference1.LogDetail LogLevel, ServiceReference1.Instance EncoreInstance, byte[] XmlIn)
        {
            ServiceReference1.Logon_With_ByteArrayRequest inValue = new ServiceReference1.Logon_With_ByteArrayRequest();
            inValue.Body = new ServiceReference1.Logon_With_ByteArrayRequestBody();
            inValue.Body.OperatorCode = OperatorCode;
            inValue.Body.OperatorPassword = OperatorPassword;
            inValue.Body.CompanyId = CompanyId;
            inValue.Body.CompanyPassword = CompanyPassword;
            inValue.Body.LanguageCode = LanguageCode;
            inValue.Body.LogLevel = LogLevel;
            inValue.Body.EncoreInstance = EncoreInstance;
            inValue.Body.XmlIn = XmlIn;
            return ((ServiceReference1.utilitiesclassSoap)(this)).Logon_With_ByteArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.LogoffResponse ServiceReference1.utilitiesclassSoap.Logoff(ServiceReference1.LogoffRequest request)
        {
            return base.Channel.Logoff(request);
        }
        
        public string Logoff(string UserId)
        {
            ServiceReference1.LogoffRequest inValue = new ServiceReference1.LogoffRequest();
            inValue.Body = new ServiceReference1.LogoffRequestBody();
            inValue.Body.UserId = UserId;
            ServiceReference1.LogoffResponse retVal = ((ServiceReference1.utilitiesclassSoap)(this)).Logoff(inValue);
            return retVal.Body.LogoffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.LogoffResponse> ServiceReference1.utilitiesclassSoap.LogoffAsync(ServiceReference1.LogoffRequest request)
        {
            return base.Channel.LogoffAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.LogoffResponse> LogoffAsync(string UserId)
        {
            ServiceReference1.LogoffRequest inValue = new ServiceReference1.LogoffRequest();
            inValue.Body = new ServiceReference1.LogoffRequestBody();
            inValue.Body.UserId = UserId;
            return ((ServiceReference1.utilitiesclassSoap)(this)).LogoffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetLogonProfileResponse ServiceReference1.utilitiesclassSoap.GetLogonProfile(ServiceReference1.GetLogonProfileRequest request)
        {
            return base.Channel.GetLogonProfile(request);
        }
        
        public string GetLogonProfile(string UserId)
        {
            ServiceReference1.GetLogonProfileRequest inValue = new ServiceReference1.GetLogonProfileRequest();
            inValue.Body = new ServiceReference1.GetLogonProfileRequestBody();
            inValue.Body.UserId = UserId;
            ServiceReference1.GetLogonProfileResponse retVal = ((ServiceReference1.utilitiesclassSoap)(this)).GetLogonProfile(inValue);
            return retVal.Body.GetLogonProfileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetLogonProfileResponse> ServiceReference1.utilitiesclassSoap.GetLogonProfileAsync(ServiceReference1.GetLogonProfileRequest request)
        {
            return base.Channel.GetLogonProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetLogonProfileResponse> GetLogonProfileAsync(string UserId)
        {
            ServiceReference1.GetLogonProfileRequest inValue = new ServiceReference1.GetLogonProfileRequest();
            inValue.Body = new ServiceReference1.GetLogonProfileRequestBody();
            inValue.Body.UserId = UserId;
            return ((ServiceReference1.utilitiesclassSoap)(this)).GetLogonProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetLogonProfileWResponse ServiceReference1.utilitiesclassSoap.GetLogonProfileW(ServiceReference1.GetLogonProfileWRequest request)
        {
            return base.Channel.GetLogonProfileW(request);
        }
        
        public byte[] GetLogonProfileW(string UserId)
        {
            ServiceReference1.GetLogonProfileWRequest inValue = new ServiceReference1.GetLogonProfileWRequest();
            inValue.Body = new ServiceReference1.GetLogonProfileWRequestBody();
            inValue.Body.UserId = UserId;
            ServiceReference1.GetLogonProfileWResponse retVal = ((ServiceReference1.utilitiesclassSoap)(this)).GetLogonProfileW(inValue);
            return retVal.Body.GetLogonProfileWResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetLogonProfileWResponse> ServiceReference1.utilitiesclassSoap.GetLogonProfileWAsync(ServiceReference1.GetLogonProfileWRequest request)
        {
            return base.Channel.GetLogonProfileWAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetLogonProfileWResponse> GetLogonProfileWAsync(string UserId)
        {
            ServiceReference1.GetLogonProfileWRequest inValue = new ServiceReference1.GetLogonProfileWRequest();
            inValue.Body = new ServiceReference1.GetLogonProfileWRequestBody();
            inValue.Body.UserId = UserId;
            return ((ServiceReference1.utilitiesclassSoap)(this)).GetLogonProfileWAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetLogonProfile_With_StringResponse ServiceReference1.utilitiesclassSoap.GetLogonProfile_With_String(ServiceReference1.GetLogonProfile_With_StringRequest request)
        {
            return base.Channel.GetLogonProfile_With_String(request);
        }
        
        public string GetLogonProfile_With_String(string UserId)
        {
            ServiceReference1.GetLogonProfile_With_StringRequest inValue = new ServiceReference1.GetLogonProfile_With_StringRequest();
            inValue.Body = new ServiceReference1.GetLogonProfile_With_StringRequestBody();
            inValue.Body.UserId = UserId;
            ServiceReference1.GetLogonProfile_With_StringResponse retVal = ((ServiceReference1.utilitiesclassSoap)(this)).GetLogonProfile_With_String(inValue);
            return retVal.Body.GetLogonProfile_With_StringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetLogonProfile_With_StringResponse> ServiceReference1.utilitiesclassSoap.GetLogonProfile_With_StringAsync(ServiceReference1.GetLogonProfile_With_StringRequest request)
        {
            return base.Channel.GetLogonProfile_With_StringAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetLogonProfile_With_StringResponse> GetLogonProfile_With_StringAsync(string UserId)
        {
            ServiceReference1.GetLogonProfile_With_StringRequest inValue = new ServiceReference1.GetLogonProfile_With_StringRequest();
            inValue.Body = new ServiceReference1.GetLogonProfile_With_StringRequestBody();
            inValue.Body.UserId = UserId;
            return ((ServiceReference1.utilitiesclassSoap)(this)).GetLogonProfile_With_StringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetLogonProfile_With_ByteArrayResponse ServiceReference1.utilitiesclassSoap.GetLogonProfile_With_ByteArray(ServiceReference1.GetLogonProfile_With_ByteArrayRequest request)
        {
            return base.Channel.GetLogonProfile_With_ByteArray(request);
        }
        
        public byte[] GetLogonProfile_With_ByteArray(string UserId)
        {
            ServiceReference1.GetLogonProfile_With_ByteArrayRequest inValue = new ServiceReference1.GetLogonProfile_With_ByteArrayRequest();
            inValue.Body = new ServiceReference1.GetLogonProfile_With_ByteArrayRequestBody();
            inValue.Body.UserId = UserId;
            ServiceReference1.GetLogonProfile_With_ByteArrayResponse retVal = ((ServiceReference1.utilitiesclassSoap)(this)).GetLogonProfile_With_ByteArray(inValue);
            return retVal.Body.GetLogonProfile_With_ByteArrayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetLogonProfile_With_ByteArrayResponse> ServiceReference1.utilitiesclassSoap.GetLogonProfile_With_ByteArrayAsync(ServiceReference1.GetLogonProfile_With_ByteArrayRequest request)
        {
            return base.Channel.GetLogonProfile_With_ByteArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetLogonProfile_With_ByteArrayResponse> GetLogonProfile_With_ByteArrayAsync(string UserId)
        {
            ServiceReference1.GetLogonProfile_With_ByteArrayRequest inValue = new ServiceReference1.GetLogonProfile_With_ByteArrayRequest();
            inValue.Body = new ServiceReference1.GetLogonProfile_With_ByteArrayRequestBody();
            inValue.Body.UserId = UserId;
            return ((ServiceReference1.utilitiesclassSoap)(this)).GetLogonProfile_With_ByteArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.RunResponse ServiceReference1.utilitiesclassSoap.Run(ServiceReference1.RunRequest request)
        {
            return base.Channel.Run(request);
        }
        
        public string Run(string UserId, string BusinessObject, string Parameter)
        {
            ServiceReference1.RunRequest inValue = new ServiceReference1.RunRequest();
            inValue.Body = new ServiceReference1.RunRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.Parameter = Parameter;
            ServiceReference1.RunResponse retVal = ((ServiceReference1.utilitiesclassSoap)(this)).Run(inValue);
            return retVal.Body.RunResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.RunResponse> ServiceReference1.utilitiesclassSoap.RunAsync(ServiceReference1.RunRequest request)
        {
            return base.Channel.RunAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RunResponse> RunAsync(string UserId, string BusinessObject, string Parameter)
        {
            ServiceReference1.RunRequest inValue = new ServiceReference1.RunRequest();
            inValue.Body = new ServiceReference1.RunRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.Parameter = Parameter;
            return ((ServiceReference1.utilitiesclassSoap)(this)).RunAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.Run_With_StringResponse ServiceReference1.utilitiesclassSoap.Run_With_String(ServiceReference1.Run_With_StringRequest request)
        {
            return base.Channel.Run_With_String(request);
        }
        
        public string Run_With_String(string UserId, string BusinessObject, string Parameter)
        {
            ServiceReference1.Run_With_StringRequest inValue = new ServiceReference1.Run_With_StringRequest();
            inValue.Body = new ServiceReference1.Run_With_StringRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.Parameter = Parameter;
            ServiceReference1.Run_With_StringResponse retVal = ((ServiceReference1.utilitiesclassSoap)(this)).Run_With_String(inValue);
            return retVal.Body.Run_With_StringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Run_With_StringResponse> ServiceReference1.utilitiesclassSoap.Run_With_StringAsync(ServiceReference1.Run_With_StringRequest request)
        {
            return base.Channel.Run_With_StringAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Run_With_StringResponse> Run_With_StringAsync(string UserId, string BusinessObject, string Parameter)
        {
            ServiceReference1.Run_With_StringRequest inValue = new ServiceReference1.Run_With_StringRequest();
            inValue.Body = new ServiceReference1.Run_With_StringRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.Parameter = Parameter;
            return ((ServiceReference1.utilitiesclassSoap)(this)).Run_With_StringAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.utilitiesclassSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.utilitiesclassSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.utilitiesclassSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.23.157/SYSPRO8WebServices/utilities.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.utilitiesclassSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.23.157/SYSPRO8WebServices/utilities.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            utilitiesclassSoap,
            
            utilitiesclassSoap12,
        }
    }
}
