//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.syspro.com/ns/transaction/", ConfigurationName="TransactionReference.transactionclassSoap")]
    public interface transactionclassSoap
    {
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/transaction/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/Build", ReplyAction="*")]
        TransactionReference.BuildResponse Build(TransactionReference.BuildRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/Build", ReplyAction="*")]
        System.Threading.Tasks.Task<TransactionReference.BuildResponse> BuildAsync(TransactionReference.BuildRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/transaction/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/BuildW", ReplyAction="*")]
        TransactionReference.BuildWResponse BuildW(TransactionReference.BuildWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/BuildW", ReplyAction="*")]
        System.Threading.Tasks.Task<TransactionReference.BuildWResponse> BuildWAsync(TransactionReference.BuildWRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/transaction/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/Build_With_String", ReplyAction="*")]
        TransactionReference.Build_With_StringResponse Build_With_String(TransactionReference.Build_With_StringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/Build_With_String", ReplyAction="*")]
        System.Threading.Tasks.Task<TransactionReference.Build_With_StringResponse> Build_With_StringAsync(TransactionReference.Build_With_StringRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/transaction/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/Build_With_ByteArray", ReplyAction="*")]
        TransactionReference.Build_With_ByteArrayResponse Build_With_ByteArray(TransactionReference.Build_With_ByteArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/Build_With_ByteArray", ReplyAction="*")]
        System.Threading.Tasks.Task<TransactionReference.Build_With_ByteArrayResponse> Build_With_ByteArrayAsync(TransactionReference.Build_With_ByteArrayRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/transaction/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/Post", ReplyAction="*")]
        TransactionReference.PostResponse Post(TransactionReference.PostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/Post", ReplyAction="*")]
        System.Threading.Tasks.Task<TransactionReference.PostResponse> PostAsync(TransactionReference.PostRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/transaction/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/PostW", ReplyAction="*")]
        TransactionReference.PostWResponse PostW(TransactionReference.PostWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/PostW", ReplyAction="*")]
        System.Threading.Tasks.Task<TransactionReference.PostWResponse> PostWAsync(TransactionReference.PostWRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/transaction/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/Post_With_String", ReplyAction="*")]
        TransactionReference.Post_With_StringResponse Post_With_String(TransactionReference.Post_With_StringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/Post_With_String", ReplyAction="*")]
        System.Threading.Tasks.Task<TransactionReference.Post_With_StringResponse> Post_With_StringAsync(TransactionReference.Post_With_StringRequest request);
        
        // CODEGEN: Generating message contract since element name UserId from namespace http://www.syspro.com/ns/transaction/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/Post_With_ByteArray", ReplyAction="*")]
        TransactionReference.Post_With_ByteArrayResponse Post_With_ByteArray(TransactionReference.Post_With_ByteArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/transaction/Post_With_ByteArray", ReplyAction="*")]
        System.Threading.Tasks.Task<TransactionReference.Post_With_ByteArrayResponse> Post_With_ByteArrayAsync(TransactionReference.Post_With_ByteArrayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuildRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Build", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.BuildRequestBody Body;
        
        public BuildRequest()
        {
        }
        
        public BuildRequest(TransactionReference.BuildRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class BuildRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string XMLIn;
        
        public BuildRequestBody()
        {
        }
        
        public BuildRequestBody(string UserId, string BusinessObject, string XMLIn)
        {
            this.UserId = UserId;
            this.BusinessObject = BusinessObject;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuildResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuildResponse", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.BuildResponseBody Body;
        
        public BuildResponse()
        {
        }
        
        public BuildResponse(TransactionReference.BuildResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class BuildResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BuildResult;
        
        public BuildResponseBody()
        {
        }
        
        public BuildResponseBody(string BuildResult)
        {
            this.BuildResult = BuildResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuildWRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuildW", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.BuildWRequestBody Body;
        
        public BuildWRequest()
        {
        }
        
        public BuildWRequest(TransactionReference.BuildWRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class BuildWRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] XMLIn;
        
        public BuildWRequestBody()
        {
        }
        
        public BuildWRequestBody(string UserId, string BusinessObject, byte[] XMLIn)
        {
            this.UserId = UserId;
            this.BusinessObject = BusinessObject;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuildWResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuildWResponse", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.BuildWResponseBody Body;
        
        public BuildWResponse()
        {
        }
        
        public BuildWResponse(TransactionReference.BuildWResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class BuildWResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] BuildWResult;
        
        public BuildWResponseBody()
        {
        }
        
        public BuildWResponseBody(byte[] BuildWResult)
        {
            this.BuildWResult = BuildWResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Build_With_StringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Build_With_String", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.Build_With_StringRequestBody Body;
        
        public Build_With_StringRequest()
        {
        }
        
        public Build_With_StringRequest(TransactionReference.Build_With_StringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class Build_With_StringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string XMLIn;
        
        public Build_With_StringRequestBody()
        {
        }
        
        public Build_With_StringRequestBody(string UserId, string BusinessObject, string XMLIn)
        {
            this.UserId = UserId;
            this.BusinessObject = BusinessObject;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Build_With_StringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Build_With_StringResponse", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.Build_With_StringResponseBody Body;
        
        public Build_With_StringResponse()
        {
        }
        
        public Build_With_StringResponse(TransactionReference.Build_With_StringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class Build_With_StringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Build_With_StringResult;
        
        public Build_With_StringResponseBody()
        {
        }
        
        public Build_With_StringResponseBody(string Build_With_StringResult)
        {
            this.Build_With_StringResult = Build_With_StringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Build_With_ByteArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Build_With_ByteArray", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.Build_With_ByteArrayRequestBody Body;
        
        public Build_With_ByteArrayRequest()
        {
        }
        
        public Build_With_ByteArrayRequest(TransactionReference.Build_With_ByteArrayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class Build_With_ByteArrayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] XMLIn;
        
        public Build_With_ByteArrayRequestBody()
        {
        }
        
        public Build_With_ByteArrayRequestBody(string UserId, string BusinessObject, byte[] XMLIn)
        {
            this.UserId = UserId;
            this.BusinessObject = BusinessObject;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Build_With_ByteArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Build_With_ByteArrayResponse", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.Build_With_ByteArrayResponseBody Body;
        
        public Build_With_ByteArrayResponse()
        {
        }
        
        public Build_With_ByteArrayResponse(TransactionReference.Build_With_ByteArrayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class Build_With_ByteArrayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] Build_With_ByteArrayResult;
        
        public Build_With_ByteArrayResponseBody()
        {
        }
        
        public Build_With_ByteArrayResponseBody(byte[] Build_With_ByteArrayResult)
        {
            this.Build_With_ByteArrayResult = Build_With_ByteArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Post", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.PostRequestBody Body;
        
        public PostRequest()
        {
        }
        
        public PostRequest(TransactionReference.PostRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class PostRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string XMLParameters;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string XMLIn;
        
        public PostRequestBody()
        {
        }
        
        public PostRequestBody(string UserId, string BusinessObject, string XMLParameters, string XMLIn)
        {
            this.UserId = UserId;
            this.BusinessObject = BusinessObject;
            this.XMLParameters = XMLParameters;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostResponse", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.PostResponseBody Body;
        
        public PostResponse()
        {
        }
        
        public PostResponse(TransactionReference.PostResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class PostResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostResult;
        
        public PostResponseBody()
        {
        }
        
        public PostResponseBody(string PostResult)
        {
            this.PostResult = PostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostWRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostW", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.PostWRequestBody Body;
        
        public PostWRequest()
        {
        }
        
        public PostWRequest(TransactionReference.PostWRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class PostWRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] XMLParameters;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] XMLIn;
        
        public PostWRequestBody()
        {
        }
        
        public PostWRequestBody(string UserId, string BusinessObject, byte[] XMLParameters, byte[] XMLIn)
        {
            this.UserId = UserId;
            this.BusinessObject = BusinessObject;
            this.XMLParameters = XMLParameters;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostWResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostWResponse", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.PostWResponseBody Body;
        
        public PostWResponse()
        {
        }
        
        public PostWResponse(TransactionReference.PostWResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class PostWResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] PostWResult;
        
        public PostWResponseBody()
        {
        }
        
        public PostWResponseBody(byte[] PostWResult)
        {
            this.PostWResult = PostWResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Post_With_StringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Post_With_String", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.Post_With_StringRequestBody Body;
        
        public Post_With_StringRequest()
        {
        }
        
        public Post_With_StringRequest(TransactionReference.Post_With_StringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class Post_With_StringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string XMLParameters;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string XMLIn;
        
        public Post_With_StringRequestBody()
        {
        }
        
        public Post_With_StringRequestBody(string UserId, string BusinessObject, string XMLParameters, string XMLIn)
        {
            this.UserId = UserId;
            this.BusinessObject = BusinessObject;
            this.XMLParameters = XMLParameters;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Post_With_StringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Post_With_StringResponse", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.Post_With_StringResponseBody Body;
        
        public Post_With_StringResponse()
        {
        }
        
        public Post_With_StringResponse(TransactionReference.Post_With_StringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class Post_With_StringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Post_With_StringResult;
        
        public Post_With_StringResponseBody()
        {
        }
        
        public Post_With_StringResponseBody(string Post_With_StringResult)
        {
            this.Post_With_StringResult = Post_With_StringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Post_With_ByteArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Post_With_ByteArray", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.Post_With_ByteArrayRequestBody Body;
        
        public Post_With_ByteArrayRequest()
        {
        }
        
        public Post_With_ByteArrayRequest(TransactionReference.Post_With_ByteArrayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class Post_With_ByteArrayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] XMLParameters;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] XMLIn;
        
        public Post_With_ByteArrayRequestBody()
        {
        }
        
        public Post_With_ByteArrayRequestBody(string UserId, string BusinessObject, byte[] XMLParameters, byte[] XMLIn)
        {
            this.UserId = UserId;
            this.BusinessObject = BusinessObject;
            this.XMLParameters = XMLParameters;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Post_With_ByteArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Post_With_ByteArrayResponse", Namespace="http://www.syspro.com/ns/transaction/", Order=0)]
        public TransactionReference.Post_With_ByteArrayResponseBody Body;
        
        public Post_With_ByteArrayResponse()
        {
        }
        
        public Post_With_ByteArrayResponse(TransactionReference.Post_With_ByteArrayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/transaction/")]
    public partial class Post_With_ByteArrayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] Post_With_ByteArrayResult;
        
        public Post_With_ByteArrayResponseBody()
        {
        }
        
        public Post_With_ByteArrayResponseBody(byte[] Post_With_ByteArrayResult)
        {
            this.Post_With_ByteArrayResult = Post_With_ByteArrayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface transactionclassSoapChannel : TransactionReference.transactionclassSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class transactionclassSoapClient : System.ServiceModel.ClientBase<TransactionReference.transactionclassSoap>, TransactionReference.transactionclassSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public transactionclassSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(transactionclassSoapClient.GetBindingForEndpoint(endpointConfiguration), transactionclassSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public transactionclassSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(transactionclassSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public transactionclassSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(transactionclassSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public transactionclassSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransactionReference.BuildResponse TransactionReference.transactionclassSoap.Build(TransactionReference.BuildRequest request)
        {
            return base.Channel.Build(request);
        }
        
        public string Build(string UserId, string BusinessObject, string XMLIn)
        {
            TransactionReference.BuildRequest inValue = new TransactionReference.BuildRequest();
            inValue.Body = new TransactionReference.BuildRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLIn = XMLIn;
            TransactionReference.BuildResponse retVal = ((TransactionReference.transactionclassSoap)(this)).Build(inValue);
            return retVal.Body.BuildResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransactionReference.BuildResponse> TransactionReference.transactionclassSoap.BuildAsync(TransactionReference.BuildRequest request)
        {
            return base.Channel.BuildAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransactionReference.BuildResponse> BuildAsync(string UserId, string BusinessObject, string XMLIn)
        {
            TransactionReference.BuildRequest inValue = new TransactionReference.BuildRequest();
            inValue.Body = new TransactionReference.BuildRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLIn = XMLIn;
            return ((TransactionReference.transactionclassSoap)(this)).BuildAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransactionReference.BuildWResponse TransactionReference.transactionclassSoap.BuildW(TransactionReference.BuildWRequest request)
        {
            return base.Channel.BuildW(request);
        }
        
        public byte[] BuildW(string UserId, string BusinessObject, byte[] XMLIn)
        {
            TransactionReference.BuildWRequest inValue = new TransactionReference.BuildWRequest();
            inValue.Body = new TransactionReference.BuildWRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLIn = XMLIn;
            TransactionReference.BuildWResponse retVal = ((TransactionReference.transactionclassSoap)(this)).BuildW(inValue);
            return retVal.Body.BuildWResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransactionReference.BuildWResponse> TransactionReference.transactionclassSoap.BuildWAsync(TransactionReference.BuildWRequest request)
        {
            return base.Channel.BuildWAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransactionReference.BuildWResponse> BuildWAsync(string UserId, string BusinessObject, byte[] XMLIn)
        {
            TransactionReference.BuildWRequest inValue = new TransactionReference.BuildWRequest();
            inValue.Body = new TransactionReference.BuildWRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLIn = XMLIn;
            return ((TransactionReference.transactionclassSoap)(this)).BuildWAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransactionReference.Build_With_StringResponse TransactionReference.transactionclassSoap.Build_With_String(TransactionReference.Build_With_StringRequest request)
        {
            return base.Channel.Build_With_String(request);
        }
        
        public string Build_With_String(string UserId, string BusinessObject, string XMLIn)
        {
            TransactionReference.Build_With_StringRequest inValue = new TransactionReference.Build_With_StringRequest();
            inValue.Body = new TransactionReference.Build_With_StringRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLIn = XMLIn;
            TransactionReference.Build_With_StringResponse retVal = ((TransactionReference.transactionclassSoap)(this)).Build_With_String(inValue);
            return retVal.Body.Build_With_StringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransactionReference.Build_With_StringResponse> TransactionReference.transactionclassSoap.Build_With_StringAsync(TransactionReference.Build_With_StringRequest request)
        {
            return base.Channel.Build_With_StringAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransactionReference.Build_With_StringResponse> Build_With_StringAsync(string UserId, string BusinessObject, string XMLIn)
        {
            TransactionReference.Build_With_StringRequest inValue = new TransactionReference.Build_With_StringRequest();
            inValue.Body = new TransactionReference.Build_With_StringRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLIn = XMLIn;
            return ((TransactionReference.transactionclassSoap)(this)).Build_With_StringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransactionReference.Build_With_ByteArrayResponse TransactionReference.transactionclassSoap.Build_With_ByteArray(TransactionReference.Build_With_ByteArrayRequest request)
        {
            return base.Channel.Build_With_ByteArray(request);
        }
        
        public byte[] Build_With_ByteArray(string UserId, string BusinessObject, byte[] XMLIn)
        {
            TransactionReference.Build_With_ByteArrayRequest inValue = new TransactionReference.Build_With_ByteArrayRequest();
            inValue.Body = new TransactionReference.Build_With_ByteArrayRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLIn = XMLIn;
            TransactionReference.Build_With_ByteArrayResponse retVal = ((TransactionReference.transactionclassSoap)(this)).Build_With_ByteArray(inValue);
            return retVal.Body.Build_With_ByteArrayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransactionReference.Build_With_ByteArrayResponse> TransactionReference.transactionclassSoap.Build_With_ByteArrayAsync(TransactionReference.Build_With_ByteArrayRequest request)
        {
            return base.Channel.Build_With_ByteArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransactionReference.Build_With_ByteArrayResponse> Build_With_ByteArrayAsync(string UserId, string BusinessObject, byte[] XMLIn)
        {
            TransactionReference.Build_With_ByteArrayRequest inValue = new TransactionReference.Build_With_ByteArrayRequest();
            inValue.Body = new TransactionReference.Build_With_ByteArrayRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLIn = XMLIn;
            return ((TransactionReference.transactionclassSoap)(this)).Build_With_ByteArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransactionReference.PostResponse TransactionReference.transactionclassSoap.Post(TransactionReference.PostRequest request)
        {
            return base.Channel.Post(request);
        }
        
        public string Post(string UserId, string BusinessObject, string XMLParameters, string XMLIn)
        {
            TransactionReference.PostRequest inValue = new TransactionReference.PostRequest();
            inValue.Body = new TransactionReference.PostRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLParameters = XMLParameters;
            inValue.Body.XMLIn = XMLIn;
            TransactionReference.PostResponse retVal = ((TransactionReference.transactionclassSoap)(this)).Post(inValue);
            return retVal.Body.PostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransactionReference.PostResponse> TransactionReference.transactionclassSoap.PostAsync(TransactionReference.PostRequest request)
        {
            return base.Channel.PostAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransactionReference.PostResponse> PostAsync(string UserId, string BusinessObject, string XMLParameters, string XMLIn)
        {
            TransactionReference.PostRequest inValue = new TransactionReference.PostRequest();
            inValue.Body = new TransactionReference.PostRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLParameters = XMLParameters;
            inValue.Body.XMLIn = XMLIn;
            return ((TransactionReference.transactionclassSoap)(this)).PostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransactionReference.PostWResponse TransactionReference.transactionclassSoap.PostW(TransactionReference.PostWRequest request)
        {
            return base.Channel.PostW(request);
        }
        
        public byte[] PostW(string UserId, string BusinessObject, byte[] XMLParameters, byte[] XMLIn)
        {
            TransactionReference.PostWRequest inValue = new TransactionReference.PostWRequest();
            inValue.Body = new TransactionReference.PostWRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLParameters = XMLParameters;
            inValue.Body.XMLIn = XMLIn;
            TransactionReference.PostWResponse retVal = ((TransactionReference.transactionclassSoap)(this)).PostW(inValue);
            return retVal.Body.PostWResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransactionReference.PostWResponse> TransactionReference.transactionclassSoap.PostWAsync(TransactionReference.PostWRequest request)
        {
            return base.Channel.PostWAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransactionReference.PostWResponse> PostWAsync(string UserId, string BusinessObject, byte[] XMLParameters, byte[] XMLIn)
        {
            TransactionReference.PostWRequest inValue = new TransactionReference.PostWRequest();
            inValue.Body = new TransactionReference.PostWRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLParameters = XMLParameters;
            inValue.Body.XMLIn = XMLIn;
            return ((TransactionReference.transactionclassSoap)(this)).PostWAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransactionReference.Post_With_StringResponse TransactionReference.transactionclassSoap.Post_With_String(TransactionReference.Post_With_StringRequest request)
        {
            return base.Channel.Post_With_String(request);
        }
        
        public string Post_With_String(string UserId, string BusinessObject, string XMLParameters, string XMLIn)
        {
            TransactionReference.Post_With_StringRequest inValue = new TransactionReference.Post_With_StringRequest();
            inValue.Body = new TransactionReference.Post_With_StringRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLParameters = XMLParameters;
            inValue.Body.XMLIn = XMLIn;
            TransactionReference.Post_With_StringResponse retVal = ((TransactionReference.transactionclassSoap)(this)).Post_With_String(inValue);
            return retVal.Body.Post_With_StringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransactionReference.Post_With_StringResponse> TransactionReference.transactionclassSoap.Post_With_StringAsync(TransactionReference.Post_With_StringRequest request)
        {
            return base.Channel.Post_With_StringAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransactionReference.Post_With_StringResponse> Post_With_StringAsync(string UserId, string BusinessObject, string XMLParameters, string XMLIn)
        {
            TransactionReference.Post_With_StringRequest inValue = new TransactionReference.Post_With_StringRequest();
            inValue.Body = new TransactionReference.Post_With_StringRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLParameters = XMLParameters;
            inValue.Body.XMLIn = XMLIn;
            return ((TransactionReference.transactionclassSoap)(this)).Post_With_StringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransactionReference.Post_With_ByteArrayResponse TransactionReference.transactionclassSoap.Post_With_ByteArray(TransactionReference.Post_With_ByteArrayRequest request)
        {
            return base.Channel.Post_With_ByteArray(request);
        }
        
        public byte[] Post_With_ByteArray(string UserId, string BusinessObject, byte[] XMLParameters, byte[] XMLIn)
        {
            TransactionReference.Post_With_ByteArrayRequest inValue = new TransactionReference.Post_With_ByteArrayRequest();
            inValue.Body = new TransactionReference.Post_With_ByteArrayRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLParameters = XMLParameters;
            inValue.Body.XMLIn = XMLIn;
            TransactionReference.Post_With_ByteArrayResponse retVal = ((TransactionReference.transactionclassSoap)(this)).Post_With_ByteArray(inValue);
            return retVal.Body.Post_With_ByteArrayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransactionReference.Post_With_ByteArrayResponse> TransactionReference.transactionclassSoap.Post_With_ByteArrayAsync(TransactionReference.Post_With_ByteArrayRequest request)
        {
            return base.Channel.Post_With_ByteArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransactionReference.Post_With_ByteArrayResponse> Post_With_ByteArrayAsync(string UserId, string BusinessObject, byte[] XMLParameters, byte[] XMLIn)
        {
            TransactionReference.Post_With_ByteArrayRequest inValue = new TransactionReference.Post_With_ByteArrayRequest();
            inValue.Body = new TransactionReference.Post_With_ByteArrayRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.BusinessObject = BusinessObject;
            inValue.Body.XMLParameters = XMLParameters;
            inValue.Body.XMLIn = XMLIn;
            return ((TransactionReference.transactionclassSoap)(this)).Post_With_ByteArrayAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.transactionclassSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.transactionclassSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.transactionclassSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.23.157/SYSPRO8WebServices/transaction.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.transactionclassSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.23.157/SYSPRO8WebServices/transaction.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            transactionclassSoap,
            
            transactionclassSoap12,
        }
    }
}
