//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.syspro.com/ns/query/", ConfigurationName="ServiceReference2.queryclassSoap")]
    public interface queryclassSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/Browse", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.BrowseResponse> BrowseAsync(ServiceReference2.BrowseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/BrowseW", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.BrowseWResponse> BrowseWAsync(ServiceReference2.BrowseWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/Browse_With_String", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.Browse_With_StringResponse> Browse_With_StringAsync(ServiceReference2.Browse_With_StringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/Browse_With_ByteArray", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.Browse_With_ByteArrayResponse> Browse_With_ByteArrayAsync(ServiceReference2.Browse_With_ByteArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/Fetch", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.FetchResponse> FetchAsync(ServiceReference2.FetchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/FetchW", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.FetchWResponse> FetchWAsync(ServiceReference2.FetchWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/Fetch_With_String", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.Fetch_With_StringResponse> Fetch_With_StringAsync(ServiceReference2.Fetch_With_StringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/Fetch_With_ByteArray", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.Fetch_With_ByteArrayResponse> Fetch_With_ByteArrayAsync(ServiceReference2.Fetch_With_ByteArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/Query", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.QueryResponse> QueryAsync(ServiceReference2.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/QueryW", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.QueryWResponse> QueryWAsync(ServiceReference2.QueryWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/Query_With_String", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.Query_With_StringResponse> Query_With_StringAsync(ServiceReference2.Query_With_StringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/Query_With_ByteArray", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.Query_With_ByteArrayResponse> Query_With_ByteArrayAsync(ServiceReference2.Query_With_ByteArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/NextKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.NextKeyResponse> NextKeyAsync(ServiceReference2.NextKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/NextKeyW", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.NextKeyWResponse> NextKeyWAsync(ServiceReference2.NextKeyWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/NextKey_With_String", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.NextKey_With_StringResponse> NextKey_With_StringAsync(ServiceReference2.NextKey_With_StringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/NextKey_With_ByteArray", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.NextKey_With_ByteArrayResponse> NextKey_With_ByteArrayAsync(ServiceReference2.NextKey_With_ByteArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/PreviousKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.PreviousKeyResponse> PreviousKeyAsync(ServiceReference2.PreviousKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/PreviousKeyW", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.PreviousKeyWResponse> PreviousKeyWAsync(ServiceReference2.PreviousKeyWRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/PreviousKey_With_String", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.PreviousKey_With_StringResponse> PreviousKey_With_StringAsync(ServiceReference2.PreviousKey_With_StringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.syspro.com/ns/query/PreviousKey_With_ByteArray", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.PreviousKey_With_ByteArrayResponse> PreviousKey_With_ByteArrayAsync(ServiceReference2.PreviousKey_With_ByteArrayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BrowseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Browse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.BrowseRequestBody Body;
        
        public BrowseRequest()
        {
        }
        
        public BrowseRequest(ServiceReference2.BrowseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class BrowseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLIn;
        
        public BrowseRequestBody()
        {
        }
        
        public BrowseRequestBody(string UserId, string XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BrowseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BrowseResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.BrowseResponseBody Body;
        
        public BrowseResponse()
        {
        }
        
        public BrowseResponse(ServiceReference2.BrowseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class BrowseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BrowseResult;
        
        public BrowseResponseBody()
        {
        }
        
        public BrowseResponseBody(string BrowseResult)
        {
            this.BrowseResult = BrowseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BrowseWRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BrowseW", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.BrowseWRequestBody Body;
        
        public BrowseWRequest()
        {
        }
        
        public BrowseWRequest(ServiceReference2.BrowseWRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class BrowseWRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] XMLIn;
        
        public BrowseWRequestBody()
        {
        }
        
        public BrowseWRequestBody(string UserId, byte[] XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BrowseWResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BrowseWResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.BrowseWResponseBody Body;
        
        public BrowseWResponse()
        {
        }
        
        public BrowseWResponse(ServiceReference2.BrowseWResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class BrowseWResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] BrowseWResult;
        
        public BrowseWResponseBody()
        {
        }
        
        public BrowseWResponseBody(byte[] BrowseWResult)
        {
            this.BrowseWResult = BrowseWResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Browse_With_StringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Browse_With_String", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.Browse_With_StringRequestBody Body;
        
        public Browse_With_StringRequest()
        {
        }
        
        public Browse_With_StringRequest(ServiceReference2.Browse_With_StringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class Browse_With_StringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLIn;
        
        public Browse_With_StringRequestBody()
        {
        }
        
        public Browse_With_StringRequestBody(string UserId, string XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Browse_With_StringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Browse_With_StringResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.Browse_With_StringResponseBody Body;
        
        public Browse_With_StringResponse()
        {
        }
        
        public Browse_With_StringResponse(ServiceReference2.Browse_With_StringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class Browse_With_StringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Browse_With_StringResult;
        
        public Browse_With_StringResponseBody()
        {
        }
        
        public Browse_With_StringResponseBody(string Browse_With_StringResult)
        {
            this.Browse_With_StringResult = Browse_With_StringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Browse_With_ByteArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Browse_With_ByteArray", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.Browse_With_ByteArrayRequestBody Body;
        
        public Browse_With_ByteArrayRequest()
        {
        }
        
        public Browse_With_ByteArrayRequest(ServiceReference2.Browse_With_ByteArrayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class Browse_With_ByteArrayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] XMLIn;
        
        public Browse_With_ByteArrayRequestBody()
        {
        }
        
        public Browse_With_ByteArrayRequestBody(string UserId, byte[] XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Browse_With_ByteArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Browse_With_ByteArrayResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.Browse_With_ByteArrayResponseBody Body;
        
        public Browse_With_ByteArrayResponse()
        {
        }
        
        public Browse_With_ByteArrayResponse(ServiceReference2.Browse_With_ByteArrayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class Browse_With_ByteArrayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] Browse_With_ByteArrayResult;
        
        public Browse_With_ByteArrayResponseBody()
        {
        }
        
        public Browse_With_ByteArrayResponseBody(byte[] Browse_With_ByteArrayResult)
        {
            this.Browse_With_ByteArrayResult = Browse_With_ByteArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fetch", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.FetchRequestBody Body;
        
        public FetchRequest()
        {
        }
        
        public FetchRequest(ServiceReference2.FetchRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class FetchRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLIn;
        
        public FetchRequestBody()
        {
        }
        
        public FetchRequestBody(string UserId, string XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.FetchResponseBody Body;
        
        public FetchResponse()
        {
        }
        
        public FetchResponse(ServiceReference2.FetchResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class FetchResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FetchResult;
        
        public FetchResponseBody()
        {
        }
        
        public FetchResponseBody(string FetchResult)
        {
            this.FetchResult = FetchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchWRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchW", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.FetchWRequestBody Body;
        
        public FetchWRequest()
        {
        }
        
        public FetchWRequest(ServiceReference2.FetchWRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class FetchWRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] XMLIn;
        
        public FetchWRequestBody()
        {
        }
        
        public FetchWRequestBody(string UserId, byte[] XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchWResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchWResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.FetchWResponseBody Body;
        
        public FetchWResponse()
        {
        }
        
        public FetchWResponse(ServiceReference2.FetchWResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class FetchWResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] FetchWResult;
        
        public FetchWResponseBody()
        {
        }
        
        public FetchWResponseBody(byte[] FetchWResult)
        {
            this.FetchWResult = FetchWResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Fetch_With_StringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fetch_With_String", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.Fetch_With_StringRequestBody Body;
        
        public Fetch_With_StringRequest()
        {
        }
        
        public Fetch_With_StringRequest(ServiceReference2.Fetch_With_StringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class Fetch_With_StringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLIn;
        
        public Fetch_With_StringRequestBody()
        {
        }
        
        public Fetch_With_StringRequestBody(string UserId, string XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Fetch_With_StringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fetch_With_StringResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.Fetch_With_StringResponseBody Body;
        
        public Fetch_With_StringResponse()
        {
        }
        
        public Fetch_With_StringResponse(ServiceReference2.Fetch_With_StringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class Fetch_With_StringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Fetch_With_StringResult;
        
        public Fetch_With_StringResponseBody()
        {
        }
        
        public Fetch_With_StringResponseBody(string Fetch_With_StringResult)
        {
            this.Fetch_With_StringResult = Fetch_With_StringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Fetch_With_ByteArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fetch_With_ByteArray", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.Fetch_With_ByteArrayRequestBody Body;
        
        public Fetch_With_ByteArrayRequest()
        {
        }
        
        public Fetch_With_ByteArrayRequest(ServiceReference2.Fetch_With_ByteArrayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class Fetch_With_ByteArrayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] XMLIn;
        
        public Fetch_With_ByteArrayRequestBody()
        {
        }
        
        public Fetch_With_ByteArrayRequestBody(string UserId, byte[] XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Fetch_With_ByteArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fetch_With_ByteArrayResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.Fetch_With_ByteArrayResponseBody Body;
        
        public Fetch_With_ByteArrayResponse()
        {
        }
        
        public Fetch_With_ByteArrayResponse(ServiceReference2.Fetch_With_ByteArrayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class Fetch_With_ByteArrayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] Fetch_With_ByteArrayResult;
        
        public Fetch_With_ByteArrayResponseBody()
        {
        }
        
        public Fetch_With_ByteArrayResponseBody(byte[] Fetch_With_ByteArrayResult)
        {
            this.Fetch_With_ByteArrayResult = Fetch_With_ByteArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Query", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.QueryRequestBody Body;
        
        public QueryRequest()
        {
        }
        
        public QueryRequest(ServiceReference2.QueryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class QueryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string XMLIn;
        
        public QueryRequestBody()
        {
        }
        
        public QueryRequestBody(string UserId, string BusinessObject, string XMLIn)
        {
            this.UserId = UserId;
            this.BusinessObject = BusinessObject;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.QueryResponseBody Body;
        
        public QueryResponse()
        {
        }
        
        public QueryResponse(ServiceReference2.QueryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class QueryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QueryResult;
        
        public QueryResponseBody()
        {
        }
        
        public QueryResponseBody(string QueryResult)
        {
            this.QueryResult = QueryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryWRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryW", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.QueryWRequestBody Body;
        
        public QueryWRequest()
        {
        }
        
        public QueryWRequest(ServiceReference2.QueryWRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class QueryWRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] XMLIn;
        
        public QueryWRequestBody()
        {
        }
        
        public QueryWRequestBody(string UserId, string BusinessObject, byte[] XMLIn)
        {
            this.UserId = UserId;
            this.BusinessObject = BusinessObject;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryWResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryWResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.QueryWResponseBody Body;
        
        public QueryWResponse()
        {
        }
        
        public QueryWResponse(ServiceReference2.QueryWResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class QueryWResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] QueryWResult;
        
        public QueryWResponseBody()
        {
        }
        
        public QueryWResponseBody(byte[] QueryWResult)
        {
            this.QueryWResult = QueryWResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Query_With_StringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Query_With_String", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.Query_With_StringRequestBody Body;
        
        public Query_With_StringRequest()
        {
        }
        
        public Query_With_StringRequest(ServiceReference2.Query_With_StringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class Query_With_StringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string XMLIn;
        
        public Query_With_StringRequestBody()
        {
        }
        
        public Query_With_StringRequestBody(string UserId, string BusinessObject, string XMLIn)
        {
            this.UserId = UserId;
            this.BusinessObject = BusinessObject;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Query_With_StringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Query_With_StringResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.Query_With_StringResponseBody Body;
        
        public Query_With_StringResponse()
        {
        }
        
        public Query_With_StringResponse(ServiceReference2.Query_With_StringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class Query_With_StringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Query_With_StringResult;
        
        public Query_With_StringResponseBody()
        {
        }
        
        public Query_With_StringResponseBody(string Query_With_StringResult)
        {
            this.Query_With_StringResult = Query_With_StringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Query_With_ByteArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Query_With_ByteArray", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.Query_With_ByteArrayRequestBody Body;
        
        public Query_With_ByteArrayRequest()
        {
        }
        
        public Query_With_ByteArrayRequest(ServiceReference2.Query_With_ByteArrayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class Query_With_ByteArrayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BusinessObject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] XMLIn;
        
        public Query_With_ByteArrayRequestBody()
        {
        }
        
        public Query_With_ByteArrayRequestBody(string UserId, string BusinessObject, byte[] XMLIn)
        {
            this.UserId = UserId;
            this.BusinessObject = BusinessObject;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Query_With_ByteArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Query_With_ByteArrayResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.Query_With_ByteArrayResponseBody Body;
        
        public Query_With_ByteArrayResponse()
        {
        }
        
        public Query_With_ByteArrayResponse(ServiceReference2.Query_With_ByteArrayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class Query_With_ByteArrayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] Query_With_ByteArrayResult;
        
        public Query_With_ByteArrayResponseBody()
        {
        }
        
        public Query_With_ByteArrayResponseBody(byte[] Query_With_ByteArrayResult)
        {
            this.Query_With_ByteArrayResult = Query_With_ByteArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NextKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NextKey", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.NextKeyRequestBody Body;
        
        public NextKeyRequest()
        {
        }
        
        public NextKeyRequest(ServiceReference2.NextKeyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class NextKeyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLIn;
        
        public NextKeyRequestBody()
        {
        }
        
        public NextKeyRequestBody(string UserId, string XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NextKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NextKeyResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.NextKeyResponseBody Body;
        
        public NextKeyResponse()
        {
        }
        
        public NextKeyResponse(ServiceReference2.NextKeyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class NextKeyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NextKeyResult;
        
        public NextKeyResponseBody()
        {
        }
        
        public NextKeyResponseBody(string NextKeyResult)
        {
            this.NextKeyResult = NextKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NextKeyWRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NextKeyW", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.NextKeyWRequestBody Body;
        
        public NextKeyWRequest()
        {
        }
        
        public NextKeyWRequest(ServiceReference2.NextKeyWRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class NextKeyWRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] XMLIn;
        
        public NextKeyWRequestBody()
        {
        }
        
        public NextKeyWRequestBody(string UserId, byte[] XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NextKeyWResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NextKeyWResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.NextKeyWResponseBody Body;
        
        public NextKeyWResponse()
        {
        }
        
        public NextKeyWResponse(ServiceReference2.NextKeyWResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class NextKeyWResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] NextKeyWResult;
        
        public NextKeyWResponseBody()
        {
        }
        
        public NextKeyWResponseBody(byte[] NextKeyWResult)
        {
            this.NextKeyWResult = NextKeyWResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NextKey_With_StringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NextKey_With_String", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.NextKey_With_StringRequestBody Body;
        
        public NextKey_With_StringRequest()
        {
        }
        
        public NextKey_With_StringRequest(ServiceReference2.NextKey_With_StringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class NextKey_With_StringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLIn;
        
        public NextKey_With_StringRequestBody()
        {
        }
        
        public NextKey_With_StringRequestBody(string UserId, string XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NextKey_With_StringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NextKey_With_StringResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.NextKey_With_StringResponseBody Body;
        
        public NextKey_With_StringResponse()
        {
        }
        
        public NextKey_With_StringResponse(ServiceReference2.NextKey_With_StringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class NextKey_With_StringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NextKey_With_StringResult;
        
        public NextKey_With_StringResponseBody()
        {
        }
        
        public NextKey_With_StringResponseBody(string NextKey_With_StringResult)
        {
            this.NextKey_With_StringResult = NextKey_With_StringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NextKey_With_ByteArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NextKey_With_ByteArray", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.NextKey_With_ByteArrayRequestBody Body;
        
        public NextKey_With_ByteArrayRequest()
        {
        }
        
        public NextKey_With_ByteArrayRequest(ServiceReference2.NextKey_With_ByteArrayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class NextKey_With_ByteArrayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] XMLIn;
        
        public NextKey_With_ByteArrayRequestBody()
        {
        }
        
        public NextKey_With_ByteArrayRequestBody(string UserId, byte[] XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NextKey_With_ByteArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NextKey_With_ByteArrayResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.NextKey_With_ByteArrayResponseBody Body;
        
        public NextKey_With_ByteArrayResponse()
        {
        }
        
        public NextKey_With_ByteArrayResponse(ServiceReference2.NextKey_With_ByteArrayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class NextKey_With_ByteArrayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] NextKey_With_ByteArrayResult;
        
        public NextKey_With_ByteArrayResponseBody()
        {
        }
        
        public NextKey_With_ByteArrayResponseBody(byte[] NextKey_With_ByteArrayResult)
        {
            this.NextKey_With_ByteArrayResult = NextKey_With_ByteArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PreviousKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PreviousKey", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.PreviousKeyRequestBody Body;
        
        public PreviousKeyRequest()
        {
        }
        
        public PreviousKeyRequest(ServiceReference2.PreviousKeyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class PreviousKeyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLIn;
        
        public PreviousKeyRequestBody()
        {
        }
        
        public PreviousKeyRequestBody(string UserId, string XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PreviousKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PreviousKeyResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.PreviousKeyResponseBody Body;
        
        public PreviousKeyResponse()
        {
        }
        
        public PreviousKeyResponse(ServiceReference2.PreviousKeyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class PreviousKeyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PreviousKeyResult;
        
        public PreviousKeyResponseBody()
        {
        }
        
        public PreviousKeyResponseBody(string PreviousKeyResult)
        {
            this.PreviousKeyResult = PreviousKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PreviousKeyWRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PreviousKeyW", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.PreviousKeyWRequestBody Body;
        
        public PreviousKeyWRequest()
        {
        }
        
        public PreviousKeyWRequest(ServiceReference2.PreviousKeyWRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class PreviousKeyWRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] XMLIn;
        
        public PreviousKeyWRequestBody()
        {
        }
        
        public PreviousKeyWRequestBody(string UserId, byte[] XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PreviousKeyWResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PreviousKeyWResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.PreviousKeyWResponseBody Body;
        
        public PreviousKeyWResponse()
        {
        }
        
        public PreviousKeyWResponse(ServiceReference2.PreviousKeyWResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class PreviousKeyWResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] PreviousKeyWResult;
        
        public PreviousKeyWResponseBody()
        {
        }
        
        public PreviousKeyWResponseBody(byte[] PreviousKeyWResult)
        {
            this.PreviousKeyWResult = PreviousKeyWResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PreviousKey_With_StringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PreviousKey_With_String", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.PreviousKey_With_StringRequestBody Body;
        
        public PreviousKey_With_StringRequest()
        {
        }
        
        public PreviousKey_With_StringRequest(ServiceReference2.PreviousKey_With_StringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class PreviousKey_With_StringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string XMLIn;
        
        public PreviousKey_With_StringRequestBody()
        {
        }
        
        public PreviousKey_With_StringRequestBody(string UserId, string XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PreviousKey_With_StringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PreviousKey_With_StringResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.PreviousKey_With_StringResponseBody Body;
        
        public PreviousKey_With_StringResponse()
        {
        }
        
        public PreviousKey_With_StringResponse(ServiceReference2.PreviousKey_With_StringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class PreviousKey_With_StringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PreviousKey_With_StringResult;
        
        public PreviousKey_With_StringResponseBody()
        {
        }
        
        public PreviousKey_With_StringResponseBody(string PreviousKey_With_StringResult)
        {
            this.PreviousKey_With_StringResult = PreviousKey_With_StringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PreviousKey_With_ByteArrayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PreviousKey_With_ByteArray", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.PreviousKey_With_ByteArrayRequestBody Body;
        
        public PreviousKey_With_ByteArrayRequest()
        {
        }
        
        public PreviousKey_With_ByteArrayRequest(ServiceReference2.PreviousKey_With_ByteArrayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class PreviousKey_With_ByteArrayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] XMLIn;
        
        public PreviousKey_With_ByteArrayRequestBody()
        {
        }
        
        public PreviousKey_With_ByteArrayRequestBody(string UserId, byte[] XMLIn)
        {
            this.UserId = UserId;
            this.XMLIn = XMLIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PreviousKey_With_ByteArrayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PreviousKey_With_ByteArrayResponse", Namespace="http://www.syspro.com/ns/query/", Order=0)]
        public ServiceReference2.PreviousKey_With_ByteArrayResponseBody Body;
        
        public PreviousKey_With_ByteArrayResponse()
        {
        }
        
        public PreviousKey_With_ByteArrayResponse(ServiceReference2.PreviousKey_With_ByteArrayResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.syspro.com/ns/query/")]
    public partial class PreviousKey_With_ByteArrayResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] PreviousKey_With_ByteArrayResult;
        
        public PreviousKey_With_ByteArrayResponseBody()
        {
        }
        
        public PreviousKey_With_ByteArrayResponseBody(byte[] PreviousKey_With_ByteArrayResult)
        {
            this.PreviousKey_With_ByteArrayResult = PreviousKey_With_ByteArrayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface queryclassSoapChannel : ServiceReference2.queryclassSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class queryclassSoapClient : System.ServiceModel.ClientBase<ServiceReference2.queryclassSoap>, ServiceReference2.queryclassSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public queryclassSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(queryclassSoapClient.GetBindingForEndpoint(endpointConfiguration), queryclassSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public queryclassSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(queryclassSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public queryclassSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(queryclassSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public queryclassSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.BrowseResponse> BrowseAsync(ServiceReference2.BrowseRequest request)
        {
            return base.Channel.BrowseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.BrowseWResponse> BrowseWAsync(ServiceReference2.BrowseWRequest request)
        {
            return base.Channel.BrowseWAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Browse_With_StringResponse> Browse_With_StringAsync(ServiceReference2.Browse_With_StringRequest request)
        {
            return base.Channel.Browse_With_StringAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Browse_With_ByteArrayResponse> Browse_With_ByteArrayAsync(ServiceReference2.Browse_With_ByteArrayRequest request)
        {
            return base.Channel.Browse_With_ByteArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.FetchResponse> FetchAsync(ServiceReference2.FetchRequest request)
        {
            return base.Channel.FetchAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.FetchWResponse> FetchWAsync(ServiceReference2.FetchWRequest request)
        {
            return base.Channel.FetchWAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Fetch_With_StringResponse> Fetch_With_StringAsync(ServiceReference2.Fetch_With_StringRequest request)
        {
            return base.Channel.Fetch_With_StringAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Fetch_With_ByteArrayResponse> Fetch_With_ByteArrayAsync(ServiceReference2.Fetch_With_ByteArrayRequest request)
        {
            return base.Channel.Fetch_With_ByteArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.QueryResponse> QueryAsync(ServiceReference2.QueryRequest request)
        {
            return base.Channel.QueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.QueryWResponse> QueryWAsync(ServiceReference2.QueryWRequest request)
        {
            return base.Channel.QueryWAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Query_With_StringResponse> Query_With_StringAsync(ServiceReference2.Query_With_StringRequest request)
        {
            return base.Channel.Query_With_StringAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Query_With_ByteArrayResponse> Query_With_ByteArrayAsync(ServiceReference2.Query_With_ByteArrayRequest request)
        {
            return base.Channel.Query_With_ByteArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.NextKeyResponse> NextKeyAsync(ServiceReference2.NextKeyRequest request)
        {
            return base.Channel.NextKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.NextKeyWResponse> NextKeyWAsync(ServiceReference2.NextKeyWRequest request)
        {
            return base.Channel.NextKeyWAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.NextKey_With_StringResponse> NextKey_With_StringAsync(ServiceReference2.NextKey_With_StringRequest request)
        {
            return base.Channel.NextKey_With_StringAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.NextKey_With_ByteArrayResponse> NextKey_With_ByteArrayAsync(ServiceReference2.NextKey_With_ByteArrayRequest request)
        {
            return base.Channel.NextKey_With_ByteArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.PreviousKeyResponse> PreviousKeyAsync(ServiceReference2.PreviousKeyRequest request)
        {
            return base.Channel.PreviousKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.PreviousKeyWResponse> PreviousKeyWAsync(ServiceReference2.PreviousKeyWRequest request)
        {
            return base.Channel.PreviousKeyWAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.PreviousKey_With_StringResponse> PreviousKey_With_StringAsync(ServiceReference2.PreviousKey_With_StringRequest request)
        {
            return base.Channel.PreviousKey_With_StringAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.PreviousKey_With_ByteArrayResponse> PreviousKey_With_ByteArrayAsync(ServiceReference2.PreviousKey_With_ByteArrayRequest request)
        {
            return base.Channel.PreviousKey_With_ByteArrayAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.queryclassSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.queryclassSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.queryclassSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.23.157/SYSPRO8WebServices/Query.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.queryclassSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.23.157/SYSPRO8WebServices/Query.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            queryclassSoap,
            
            queryclassSoap12,
        }
    }
}
